### ISSUE TITLE
Compatibility with Authelia OIDC ?

### ISSUE THREAD

**Issue by skuizy** [robrotheram/taiga-contrib-openid-auth#47]
I get the folowing error when trying to connect through Authelia : 
`Authorization Request failed with error: The state is missing or does not have enough characters and is therefore considered too weak. Request parameter 'state' must be at least be 8 characters long to ensure sufficient entropy.`

Here's my docker-compose :
```
x-environment:
  &default-back-environment
  TAIGA_SECRET_KEY: "${SECRET_KEY}"
  TAIGA_SITES_SCHEME: "${TAIGA_SCHEME}"
  TAIGA_SITES_DOMAIN: "${TAIGA_DOMAIN}"
  TAIGA_SUBPATH: "${SUBPATH}"
  DEFAULT_FROM_EMAIL: "${EMAIL_DEFAULT_FROM}"
  ENABLE_OPENID: "True"
  OPENID_URL: "https://authelia.domain/api/oidc/authorization"
  OPENID_USER_URL: "https://authelia.domain/api/oidc/userinfo"
  OPENID_TOKEN_URL: "https://authelia.domain/api/oidc/token"
  OPENID_CLIENT_ID: "taiga"
  OPENID_CLIENT_SECRET: "redacted"
  OPENID_NAME: "taiga"
  OPENID_FILTER: "admin"
  OPENID_FILTER_FIELD: "groups"
  PUBLIC_REGISTER_ENABLED: "True"

x-volumes:
  &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media

services:
  taiga:
    image: nginx:1.19-alpine
    volumes:
      - ./taiga/taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
    networks:
      - backend
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events
  taiga-back:
    image: robrotheram/taiga-back-openid
    environment: *default-back-environment
    env_file: .env
    volumes: *default-back-volumes
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
      taiga-events-rabbitmq:
        condition: service_started
      taiga-async-rabbitmq:
        condition: service_started
  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    env_file: .env
    volumes: *default-back-volumes
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
      taiga-events-rabbitmq:
        condition: service_started
      taiga-async-rabbitmq:
        condition: service_started
  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_VHOST}"
    hostname: "taiga-async-rabbitmq"
    volumes:
      - taiga-async-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - backend
  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_VHOST}"
    hostname: "taiga-events-rabbitmq"
    volumes:
      - taiga-events-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - backend
  taiga-front:
    image: robrotheram/taiga-front-openid
    environment:
      TAIGA_URL: "${TAIGA_SCHEME}://${TAIGA_DOMAIN}"
      TAIGA_WEBSOCKETS_URL: "${WEBSOCKETS_SCHEME}://${TAIGA_DOMAIN}"
      TAIGA_SUBPATH: "${SUBPATH}"
      ENABLE_OPENID: "true"
      OPENID_URL: "https://authelia.domain/api/oidc/authorization"
      OPENID_CLIENT_ID: "taiga"
    networks:
      - backend
    # volumes:
    #   - ./conf.json:/usr/share/nginx/html/conf.json
  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASS: "${RABBITMQ_PASS}"
      TAIGA_SECRET_KEY: "${SECRET_KEY}"
    networks:
      - backend
    depends_on:
      taiga-events-rabbitmq:
        condition: service_started
  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      MAX_AGE: "${ATTACHMENTS_MAX_AGE}"
      SECRET_KEY: "${SECRET_KEY}"
    networks:
      - backend
```

Here's my Authelia relevant configuration.yml :
```
    - id: taiga
      secret: 'redacted'
      authorization_policy: two_factor
      redirect_uris:
        - https://taiga.domain/login
      scopes:
        - openid
        - profile
        - groups
        - email
      userinfo_signing_algorithm: none
```
